language: java
sudo: false
dist: trusty

jdk:
  - oraclejdk8

services:
  - postgresql

before_script:
  - cd backend/
  - psql -c 'create database employee;' -U postgres

script:
  - mvn clean verify coveralls:report
