language: java
sudo: false
dist: trusty

jdk:
  - oraclejdk8

services:
  - postgresql

before_script:
  - cd backend/
  - psql -c 'create database employee;' -U postgres

#script:
#  - mvn clean test coveralls:report

#after_success:
#  - bash <(curl -s https://codecov.io/bash)
