version: '3.3'

services:
  postgres:
    container_name: postgres-standalone
    build:
      context: services/postgres
      dockerfile: Dockerfile
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=employee
      - POSTGRES_PASSWORD=postgres

#    volumes:
#    - data:/var/lib/postgres/data


  activemq:
    container_name: activemq-standalone
    build:
      context: services/activeMq
      dockerfile: Dockerfile
    ports:
#      ui
      - 8161:8161
#     jms
      - 61616:61616
#    volumes:
#    - data:/var/lib/activemq/data


  app:
    container_name: app-standalone
    build:
      context: services/app
      dockerfile: Dockerfile

    environment:
      - PORT=8088
      - DATASOURCE_URL=jdbc:postgresql://postgres:5432/employee?stringtype=unspecified
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres

      - SPRING_ACTIVEMQ_BROKERURL=tcp://activemq:61616
      - SPRING_ACTIVEMQ_USER=admin
      - SPRING_ACTIVEMQ_PASSWORD=admin
    image: app-img
    ports:
      - 8088:8088
      - 8090:8090
    depends_on:
      - postgres
      - activemq


  frontend:
    container_name: frontend-standalone
    build:
      context: services/frontend
      dockerfile: Dockerfile
    image: frontend-img
    ports:
      - 4200:80
    depends_on:
      - app


volumes:
  db-data:
